apiVersion: v1
kind: Secret
metadata:
  name: 1-35
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  name: 1-35   # Application destination.name 에 쓸 이름
  server: arn:aws:eks:eu-west-1:905418051405:cluster/1-35
  project: default
